version: '3.8'

services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - RASA_MODEL_PATH=/app/models
    command: ["rasa", "run", "--enable-api", "--cors", "*", "--debug"]
    networks:
      - rasa-network

  rasa-actions:
    build: .
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    command: ["rasa", "run", "actions", "--debug"]
    networks:
      - rasa-network

  rasa-x:
    image: rasa/rasa-x:1.2.0
    ports:
      - "5002:5002"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - RASA_MODEL_PATH=/app/models
      - RASA_X_HOST=0.0.0.0
    depends_on:
      - rasa
    networks:
      - rasa-network

networks:
  rasa-network:
    driver: bridge

